name: Flutter Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: stable
          cache: true
      - name: Flutter Clean
        run: flutter clean

      - name: Flutter Pub Get
        run: flutter pub upgrade && flutter pub get

      - name: Set Flutter JDK
        run: flutter config --jdk-dir $JAVA_HOME

      - name: Build APK
        run: flutter build apk --split-per-abi --verbose

      - name: Upload APK (arm64-v8a)
        uses: actions/upload-artifact@v4
        with:
          name: flutterchat-android-arm64-v8a
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Upload APK (armeabi-v7a)
        uses: actions/upload-artifact@v4
        with:
          name: flutterchat-android-armeabi-v7a
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      - name: Upload APK (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: flutterchat-android-x86_64
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk
